# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk
org.gradle.projectcachedir=/home/saolghra/.gradle-project-cache/armor-hud
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT
# Mod Properties
mod_version=3.4-26.1
maven_group=com.saolghra
archives_base_name=Armor_Hud
# Dependencies
# check this on https://modmuss50.me/fabric.html or https://fabricmc.net/develop
fabric_version=0.144.3+26.1
# ModMenu Version can be found on this modrinth page: https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=18.0.0-alpha.8
# Cloth Config Version can be found on this modrinth page: https://modrinth.com/mod/cloth-config/versions?l=fabric
cloth_config_version=26.1.154
