# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk
org.gradle.projectcachedir=/home/saolghra/.gradle-project-cache/armor-hud
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=3.4-26.2
maven_group=com.saolghra
archives_base_name=Armor_Hud
# Dependencies
# check this on https://modmuss50.me/fabric.html or https://fabricmc.net/develop
fabric_version=0.152.2+26.2
# ModMenu Version can be found on this modrinth page: https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=1.10.5
# Cloth Config Version can be found on this modrinth page: https://modrinth.com/mod/cloth-config/versions?l=fabric
cloth_config_version=26.2.155
mappings_channel=none
